services:
  database:
    image: mariadb:10.5
    container_name: database_gearledger
    env_file:
      - .env
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./healthcheck.cnf:/healthcheck.cnf:ro 
    hostname: gearledger
    ports:
      - "3306:3306"
    networks:
      - net_gearledger
    healthcheck:
        test: ["CMD", "mysqladmin", "--defaults-extra-file=/healthcheck.cnf", "ping", "-h", "localhost"]
        interval: 30s
        timeout: 10s
        retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
# --------------------------------------------------------------------
  springboot-app:
    build: .
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "9000:8080"
    networks:
      - net_gearledger
# --------------------------------------------------------------------
networks:
  net_gearledger:
      driver: bridge
      name: net_gearledger

